name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
    
    - name: Build
      run: |
        xcodebuild build -scheme SlavicWallpapers -destination 'platform=macOS'
        
    - name: Run Unit Tests
      run: |
        xcodebuild test -scheme SlavicWallpapers -destination 'platform=macOS' -only-testing:SlavicWallpapersTests
        
    - name: Run UI Tests
      run: |
        xcodebuild test -scheme SlavicWallpapers -destination 'platform=macOS' -only-testing:SlavicWallpapersUITests
        
    - name: Run SwiftLint
      run: |
        brew install swiftlint
        swiftlint lint --reporter github-actions-logging

  test:
    name: Run Tests
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Build and Test
      run: |
        xcodebuild test \
          -scheme SlavicWallpapers \
          -destination 'platform=macOS' \
          CODE_SIGN_IDENTITY=- \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          | xcpretty && exit ${PIPESTATUS[0]}
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-results
        path: ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/**/*.xcresult

  lint:
    name: SwiftLint
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
    
    - name: Run SwiftLint
      run: swiftlint lint --strict

  status-check:
    name: Status Check
    needs: [test, lint]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Check Status
      run: |
        if [ "${{ needs.test.result }}" != "success" ] || [ "${{ needs.lint.result }}" != "success" ]; then
          echo "Tests or linting failed"
          exit 1
        fi 