name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v3
    
    - name: Set Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app
      
    - name: Build and Test
      run: |
        swift build
        swift test
        
    - name: Build App
      run: |
        swift build -c release
        
    - name: Run UI Tests
      run: |
        xcodebuild test \
          -scheme SlavicWallpapers \
          -destination 'platform=macOS' \
          -only-testing:SlavicWallpapersUITests \
          CODE_SIGN_IDENTITY=- \
          CODE_SIGNING_REQUIRED=NO

  lint:
    name: SwiftLint
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
    
    - name: Run SwiftLint
      run: swiftlint lint --strict

  status-check:
    name: Status Check
    needs: [build, lint]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Check Status
      run: |
        if [ "${{ needs.build.result }}" != "success" ] || [ "${{ needs.lint.result }}" != "success" ]; then
          echo "Build or linting failed"
          exit 1
        fi 