name: Swift Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and Test
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
      
    - name: Run SwiftLint
      run: swiftlint lint --strict
      
    - name: Build
      run: xcodebuild build -scheme SlavicWallpapers -configuration Debug
      
    - name: Run Unit Tests
      run: xcodebuild test -scheme SlavicWallpapers -configuration Debug -only-testing:SlavicWallpapersTests
      
    - name: Run UI Tests
      run: |
        # Запускаем UI тесты с таймаутом и повторными попытками
        max_attempts=3
        attempt=1
        
        while [ $attempt -le $max_attempts ]; do
          echo "UI Test attempt $attempt of $max_attempts"
          if xcodebuild test -scheme SlavicWallpapers -configuration Debug -only-testing:SlavicWallpapersUITests; then
            echo "UI Tests passed"
            exit 0
          fi
          attempt=$((attempt + 1))
          sleep 5
        done
        
        echo "UI Tests failed after $max_attempts attempts"
        exit 1

  status-check:
    needs: [test]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Check Status
      run: |
        if [ "${{ needs.test.result }}" != "success" ]; then
          echo "Tests failed"
          exit 1
        fi 